name: fivebot documentation
title: fivebot
description: The fivebot 3D printer project, built on the Creality Ender 5 (Pro)
remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme
color_scheme: fivebot
url: https://fivebot-printer.github.io/fivebot
logo: /assets/images/fivebot-logo-light-bg-crop.png
markdown: kramdown
aux_links:
  "Discord":
    - "https://discord.com/invite/PU7RBwUmzd"
  "GitHub":
    - "https://github.com/fivebot-printer/fivebot"
  "Download project files":
    - "https://github.com/fivebot-printer/fivebot/zipball/main"
callouts:
  warning:
    color: red
    title: Warning
  important:
    color: yellow
    title: important
  highlight:
    color: yellow
  note:
    color: grey-lt
    title: Note
    
